name: Get Citation Data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd google_scholar_crawler
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          cd google_scholar_crawler
          python main.py

      - name: Push to repo
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add google-scholar-stats/*.json
          git commit -m "Update citation data"
          git push origin HEAD:main --force
